# Generated by Django 5.2.10 on 2026-01-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='known_languages',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='known_tools',
        ),
    ]
