# Generated by Django 5.2.10 on 2026-01-14 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_learnerprofile_known_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('total_duration', models.IntegerField(default=0)),
                ('focus_duration', models.IntegerField(default=0)),
                ('distraction_count', models.IntegerField(default=0)),
                ('focus_percentage', models.FloatField(default=100.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
    ]
