# Generated by Django 5.2.10 on 2026-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='For WhatsApp notifications (e.g., +14155552671)', max_length=20, null=True),
        ),
    ]
