# Generated by Django 5.2.10 on 2026-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_learnerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='phone_number',
            field=models.CharField(default='+919518380879', help_text='For WhatsApp notifications', max_length=20),
        ),
    ]
