# Generated by Django 5.2.10 on 2026-01-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_learnerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Unique hash for certificate verification', max_length=50, null=True, unique=True),
        ),
    ]
