# Generated by Django 5.2.10 on 2026-01-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_roadmap_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the course was completed (progress=100%)', null=True),
        ),
    ]
