# Generated by Django 5.2.10 on 2026-01-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mentorprofile_mentorslot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='title',
            field=models.CharField(default='Mentor', max_length=100),
        ),
    ]
